tap 'buo/cask-upgrade'
tap 'homebrew/services'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'olets/tap'
tap 'romkatv/powerlevel10k'

brew 'bat'
brew 'colordiff'
brew 'coreutils'
brew 'curl'
brew 'curlie'
brew 'diff-so-fancy'
brew 'dog'
brew 'dua-cli'
brew 'exa'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'git-extras'
brew 'goenv'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnupg'
brew 'goenv'
brew 'go'
brew 'grep'
brew 'htop'
brew 'httpie'
brew 'httpstat'
brew 'jq'
brew 'lesspipe'
brew 'neovim'
brew 'nmap'
brew 'node'
brew 'nodeenv'
brew 'openssh'
brew 'pipx'
brew 'powerlevel10k'
brew 'pyenv'
brew 'python3'
brew 'ripgrep'
brew 'the_silver_searcher'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'xdg-ninja'
brew 'zsh-completions'
brew 'zsh-fast-syntax-highlighting'
brew 'zsh-abbr'
brew 'zsh-autopair'
brew 'zsh-autosuggestions'

cask 'alacritty'
cask 'alfred'
cask 'bitwarden'
cask 'firefox'
cask 'font-hack-nerd-font'
cask 'postman'
cask 'rectangle'
cask 'vscodium'

# Personal. Uncomment as needed
# cask 'electrum'
# cask 'google-chrome'
# cask 'monero-wallet'
# cask 'mullvad-browser'
# cask 'knockknock'
# cask 'little-snitch'
# cask 'taskexplorer'
# cask 'transmission'
# cask 'signal'
# cask 'slack'
# cask 'taskexplorer'
# cask 'tor-browser'
# brew 'mas'
# mas 'WireGuard', id: 1451685025