brew 'bat' # Better cat
brew 'btop'
brew 'coreutils'
brew 'curl'
brew 'curlie'
brew 'direnv' # Loading .envrc files
brew 'doggo' # Better dig
brew 'dua-cli' # Better du
brew 'eza' # Better ls
brew 'fastfetch' # Get system info
brew 'fd' # better find
brew 'fzf' # Fuzzy finder
brew 'git' # More recent version of git
brew 'git-delta' # Better diff
brew 'gnu-sed'
brew 'gnu-tar'
brew 'grep'
brew 'httpstat'
brew 'neovim'
brew 'openssh'
brew 'powerlevel10k' # zsh command prompt
brew 'ripgrep' # Faster ag written in Rust
brew 'tealdeer' # tldr utility
brew 'tmux' # terminal multiplexer
brew 'tree' # Show directory trees
brew 'wget'
brew 'zoxide' # Smart cd
brew 'zsh-completions'
brew 'zsh-fast-syntax-highlighting'
brew 'olets/tap/zsh-abbr'
brew 'zsh-autopair'
brew 'zsh-autosuggestions'

cask 'alacritty' # Fast, minimal terminal
cask 'bitwarden'
cask 'electrum'
cask 'eloston-chromium'
cask 'firefox'
cask 'font-hack-nerd-font'
cask 'little-snitch'
cask 'monero-wallet'
cask 'protonvpn'
cask 'rectangle'
cask 'signal'
cask 'slack'
cask 'steam'