brew 'bat' # Better cat
brew 'coreutils'
brew 'curl'
brew 'curlie'
brew 'direnv' # Loading .envrc files
brew 'doggo' # Better dig
brew 'dua-cli' # Better du
brew 'eza' # Better ls
brew 'fd' # better find
brew 'forgit' # fzf-git integration
brew 'fzf' # Fuzzy finder
brew 'git' # More recent version of git
brew 'git-delta' # Better diff
brew 'gnu-sed'
brew 'gnu-tar'
brew 'grep'
brew 'htop'
brew 'lesspipe'
brew 'neovim'
brew 'powerlevel10k' # zsh command prompt
brew 'ripgrep' # Faster ag written in Rust
brew 'tealdeer' # tldr utility
brew 'tmux' # terminal multiplexer
brew 'zoxide' # Smart cd
brew 'zsh-completions'
brew 'zsh-autopair'
brew 'zsh-autosuggestions'

cask 'font-jetbrains-mono-nerd-font'
cask 'alacritty' # Fast, minimal terminal
cask 'rectangle'

# Personal
cask 'bitwarden'
cask 'electrum'
cask 'eloston-chromium'
cask 'firefox'
cask 'little-snitch'
cask 'monero-wallet'
cask 'protonvpn'
cask 'signal'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'vscodium'
