#!/usr/bin/env zsh

# This file configures and initializes Zsh's completion system (compinit).
# It's tuned for performance, fzf-tab, and smart matching.

# Zstyle pattern syntax, '*' matching any field:
# :completion:<function>:<completer>:<command>:<argument>:<tag>

# Colorize filenames during completion; ${(s.:.)...} splits $LS_COLORS on ':'.
zstyle ':completion:*'                  list-colors         ${(s.:.)LS_COLORS}

# Completer order. '_ignored' completes otherwise-ignored patterns (e.g. .gitignore'd
# files); '_approximate' matches misspellings.
zstyle ':completion:*'                  completer           _expand _complete _ignored _approximate

zstyle ':completion:*'                  use-cache           true
zstyle ':completion:*'                  cache-path          $XDG_CACHE_HOME/zsh/zcompcache
zstyle ':completion:*'                  list-dirs-first     on

# Case-insensitive matching: lower-case input also matches upper-case.
zstyle ':completion:*'                  matcher-list        'm:{[:lower:]}={[:upper:]}'

zstyle ':completion:*'                  add-space           true

# Group completions by their type (e.g., "aliases", "commands").
zstyle ':completion:*'                  group-name          ''

# Format descriptions, corrections, and manuals with brackets. E.g., "[directory]"
zstyle ':completion:*:descriptions'     format              '[%d]'
zstyle ':completion:*:corrections'      format              '[%d]'
zstyle ':completion:*:manuals'          separate-sections   true

# Disable sorting for command options (like -h, -v, -f).
# This is faster and often more logical (e.g., shows short/long forms together).
zstyle ':completion:complete:*:options' sort                false

# fzf-tab integration: 'menu no' disables zsh's built-in completion menu so
# fzf-tab can take over the UI — removing this breaks fzf-tab.
zstyle ':completion:*'                  menu                no

# When completing 'cd', complete command-line options (like 'cd -')
# in addition to directory names.
zstyle ':completion:*'                  complete-options    true

# When completing 'cd', don't show the "users" tag (home directories).
zstyle ':completion:*'                  tag-order           '! users'

zstyle ':completion:*:*:-command-:*:*'  group-order         aliases builtins functions commands
zstyle ':completion:*'                  keep-prefix         true

# +--------------------------------+
# | APPLICATION-SPECIFIC ZSTYLES   |
# +--------------------------------+

# --- Git Completions ---
# Don't sort 'git checkout' results (faster, shows recent branches first).
zstyle ':completion:*:git-checkout:*'   sort                false
# Complete tags as well as branches for checkout/switch.
zstyle ':completion:*:git-checkout:*'  complete-refs 'yes'
zstyle ':completion:*:git-switch:*'    complete-refs 'yes'
# Show verbose descriptions for git aliases.
zstyle ':completion:*:git:*'           verbose 'yes'

# --- Kill Completions ---
# Full command lines instead of bare PIDs — that's what fzf-tab previews.
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,command | sed "s/ $//"'
zstyle ':completion:*:kill:*' table-format 'PID:8' 'COMMAND'
zstyle ':completion:*:kill:*' sort-order 'user'

# --- SSH Completions ---
# Read SSH config and known_hosts for hostname completion.
zstyle ':completion:*:ssh:*:*' hosts-file ~/.ssh/config ~/.ssh/known_hosts

# +----------------------+
# |  COMPLETION SYSTEM   |
# +----------------------+

# Homebrew ships zsh-completions on macOS; Debian has no package (absent from
# Trixie), so install_zsh_plugins git-clones it — upstream points fpath at src/.
if [[ $OSTYPE == darwin* ]]; then
  fpath+=$HOMEBREW_PREFIX/share/zsh-completions
else
  fpath+=$XDG_DATA_HOME/zsh/plugins/zsh-completions/src
fi

# Completions generated by deploy.zsh for tools with no shipped zsh completion
fpath+=$XDG_CACHE_HOME/zsh/completions

# Load the 'complist' module, which provides extended completion list formatting.
zmodload zsh/complist

autoload -Uz compinit
local compdump_file="$XDG_CACHE_HOME/zsh/compdump"

# Regenerate the compdump at most once per ~20 hours, else load it from cache.
# '(#qN.mh+20)' is a glob qualifier: nullglob, plain files, mtime over 20 hours.
local -a stale_compdump=($compdump_file(#qN.mh+20))
if ! [[ -f "$compdump_file" ]] || [[ -n "$stale_compdump" ]]; then
    # '-i' (insecure) skips security checks — we trust our own fpath.
    compinit -i -u -d "$compdump_file"
else
    # '-C' loads the fresh compdump straight from cache.
    compinit -i -u -C -d "$compdump_file"
fi

# Pre-compile the compdump to '.zwc' — zsh loads the binary form much faster
# than parsing the text one. zrecompile skips when the .zwc is already current.
autoload -Uz zrecompile
zrecompile -pq "$compdump_file"

# Load the bash completion compatibility system as a fallback
# for tools that don't provide native Zsh completions.
autoload -Uz bashcompinit && bashcompinit
