#!/usr/bin/env zsh

# This file configures and initializes Zsh's completion system (compinit).
# It's tuned for performance, fzf-tab, and smart matching.

# Zstyle pattern syntax:
# :completion:<function>:<completer>:<command>:<argument>:<tag>
# '*' is a wildcard for any field.

# Colorize filenames during completion; ${(s.:.)...} splits $LS_COLORS on ':'.
zstyle ':completion:*'                  list-colors         ${(s.:.)LS_COLORS}

# Define the order of completion methods (completers) Zsh should try.
# _expand:       Performs glob expansions.
# _complete:     The main completion engine.
# _ignored:      Completes ignored patterns (e.g., files in .gitignore).
# _approximate:  Tries to find approximate/misspelled matches.
zstyle ':completion:*'                  completer           _expand _complete _ignored _approximate

zstyle ':completion:*'                  use-cache           true
zstyle ':completion:*'                  cache-path          $XDG_CACHE_HOME/zsh/zcompcache
zstyle ':completion:*'                  list-dirs-first     on

# Case-insensitive matching: lower-case input also matches upper-case.
zstyle ':completion:*'                  matcher-list        'm:{[:lower:]}={[:upper:]}'

zstyle ':completion:*'                  add-space           true

# Group completions by their type (e.g., "aliases", "commands").
zstyle ':completion:*'                  group-name          ''

# Format descriptions, corrections, and manuals with brackets. E.g., "[directory]"
zstyle ':completion:*:descriptions'     format              '[%d]'
zstyle ':completion:*:corrections'      format              '[%d]'
zstyle ':completion:*:manuals'          separate-sections   true

# Disable sorting for command options (like -h, -v, -f).
# This is faster and often more logical (e.g., shows short/long forms together).
zstyle ':completion:complete:*:options' sort                false

# fzf-tab integration: 'menu no' disables zsh's built-in completion menu so
# fzf-tab can take over the UI — removing this breaks fzf-tab.
zstyle ':completion:*'                  menu                no

# When completing 'cd', complete command-line options (like 'cd -')
# in addition to directory names.
zstyle ':completion:*'                  complete-options    true

# When completing 'cd', don't show the "users" tag (home directories).
zstyle ':completion:*'                  tag-order           '! users'

zstyle ':completion:*:*:-command-:*:*'  group-order         aliases builtins functions commands
zstyle ':completion:*'                  keep-prefix         true

# +--------------------------------+
# | APPLICATION-SPECIFIC ZSTYLES   |
# +--------------------------------+

# --- Git Completions ---
# Don't sort 'git checkout' results (faster, shows recent branches first).
zstyle ':completion:*:git-checkout:*'   sort                false
# Complete tags as well as branches for checkout/switch.
zstyle ':completion:*:git-checkout:*'  complete-refs 'yes'
zstyle ':completion:*:git-switch:*'    complete-refs 'yes'
# Show verbose descriptions for git aliases.
zstyle ':completion:*:git:*'           verbose 'yes'

# --- Kill Completions ---
# Show full command lines for 'kill' targets instead of just PIDs.
# This feeds rich data directly into fzf-tab.
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,command | sed "s/ $//"'
zstyle ':completion:*:kill:*' table-format 'PID:8' 'COMMAND'
zstyle ':completion:*:kill:*' sort-order 'user'

# --- SSH Completions ---
# Read SSH config and known_hosts for hostname completion.
zstyle ':completion:*:ssh:*:*' hosts-file ~/.ssh/config ~/.ssh/known_hosts

# +----------------------+
# |  COMPLETION SYSTEM   |
# +----------------------+

# Add zsh-completions to the function path. Homebrew ships it on macOS; on
# Linux there's no reliable apt package (absent from Trixie's archive
# entirely), so install_zsh_plugins git-clones it like the other plugins —
# upstream's own install instructions point fpath at its src/ subdirectory.
if [[ $OSTYPE == darwin* ]]; then
  fpath+=$HOMEBREW_PREFIX/share/zsh-completions
else
  fpath+=$XDG_DATA_HOME/zsh/plugins/zsh-completions/src
fi

# Completions generated by deploy.zsh for tools with no shipped zsh completion
fpath+=$XDG_CACHE_HOME/zsh/completions

# Load the 'complist' module, which provides extended completion list formatting.
zmodload zsh/complist

autoload -Uz compinit
local compdump_file="$XDG_CACHE_HOME/zsh/compdump"

# Regenerate the compdump at most once per ~20 hours; otherwise load it
# straight from cache. `($compdump_file(#qN.mh+20))` is a glob qualifier:
#   #q -> Quiet
#   N  -> NULL_GLOB (return nothing if no match, prevents error)
#   .  -> Plain files only
#   mh -> Modified time, in hours
#   +20 -> More than 20 hours ago
local -a stale_compdump=($compdump_file(#qN.mh+20))
if ! [[ -f "$compdump_file" ]] || [[ -n "$stale_compdump" ]]; then
    # '-i' (insecure) skips security checks — we trust our own fpath.
    compinit -i -u -d "$compdump_file"
else
    # '-C' loads the fresh compdump straight from cache.
    compinit -i -u -C -d "$compdump_file"
fi

# Pre-compile the compdump file into a '.zwc' file.
# Zsh loads the binary '.zwc' file much faster than parsing the text compdump.
# 'zrecompile' is smart and will skip if the .zwc is already up-to-date.
autoload -Uz zrecompile
zrecompile -pq "$compdump_file"

# Load the bash completion compatibility system as a fallback
# for tools that don't provide native Zsh completions.
autoload -Uz bashcompinit && bashcompinit   