# .zshenv is sourced on all shell invocations: interactive, non-interactive, and scripts.
# Set environment variables, paths, and tool configuration here.
# No output, no tty assumptions — this file runs before everything else.

# +-----------+
# | BOOTSTRAP |
# +-----------+

# Resolve ZDOTDIR from this file's own path so zsh can locate the rest of the config
local homezshenv=$HOME/.zshenv
export ZDOTDIR=$homezshenv:A:h

# DOTFILES is the parent of ZDOTDIR
export DOTFILES=$ZDOTDIR:h

# Prevent zsh from sourcing /etc/zprofile, /etc/zshrc, etc.
unsetopt GLOBAL_RCS

# +---------------+
# | CORE PROGRAMS |
# +---------------+

export EDITOR=nvim
export VISUAL=$EDITOR
export PAGER=less

# col -bx strips groff backspace markup; bat renders with man syntax highlighting
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# less: colors, smart-case search, mouse scroll, quit if output fits one screen
export LESS="--RAW-CONTROL-CHARS --quit-if-one-screen --ignore-case --hilite-unread --LONG-PROMPT --window=-4 --tabs=4 --mouse --wheel-lines=3"

# Allow less to open non-text files (archives, images, etc.) via lesspipe
export LESSOPEN="|lesspipe.sh %s"

# `< file` pages through $PAGER
export READNULLCMD=$PAGER

# +--------------------+
# | XDG BASE DIRS      |
# +--------------------+

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_RUNTIME_DIR=$TMPDIR

# +----------------+
# | XDG COMPLIANCE |
# +----------------+

# Override tool defaults so they write inside XDG dirs instead of $HOME
export HISTFILE=$XDG_STATE_HOME/zsh/history
export LESSHISTFILE=$XDG_STATE_HOME/less/history
export HTOPRC=$XDG_CONFIG_HOME/htop/htoprc
export RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/ripgrep/config
export TEALDEER_CONFIG_DIR=$XDG_CONFIG_HOME/tealdeer
export TERMINFO=$XDG_DATA_HOME/terminfo
export TMUX_TMPDIR=$XDG_RUNTIME_DIR/tmux
export ELECTRUMDIR=$XDG_DATA_HOME/electrum
export _ZO_DATA_DIR=$XDG_DATA_HOME/zoxide

# +----------+
# | HOMEBREW |
# +----------+

# Keep Homebrew's cache, logs, and temp under XDG dirs (brew.env can't expand vars)
export HOMEBREW_CACHE=$XDG_CACHE_HOME/Homebrew
export HOMEBREW_LOGS=$XDG_STATE_HOME/Homebrew/logs
export HOMEBREW_TEMP=$XDG_RUNTIME_DIR/Homebrew

# Sets HOMEBREW_PREFIX, HOMEBREW_CELLAR, HOMEBREW_REPOSITORY, PATH, MANPATH, INFOPATH
eval $(/opt/homebrew/bin/brew shellenv)

# +------+
# | PATH |
# +------+

# Enforce uniqueness on path arrays before any additions
typeset -U path fpath manpath

# Prefer GNU coreutils over macOS BSD versions (provides un-prefixed names: sed, tar, etc.)
for bindir in $HOMEBREW_PREFIX/opt/*/libexec/gnubin; do path=($bindir $path); done
for mandir in $HOMEBREW_PREFIX/opt/*/libexec/gnuman; do manpath=($mandir $manpath); done

# Remaining Homebrew opt package binaries and man pages
for bindir in $HOMEBREW_PREFIX/opt/*/bin; do path=($bindir $path); done
for mandir in $HOMEBREW_PREFIX/opt/*/share/man/man1; do manpath=($mandir $manpath); done

# User-local binaries and scripts
path+=$HOME/.local/bin

# Custom zsh functions and completion definitions
fpath+=$ZDOTDIR/fpath

# +-----------+
# | LS COLORS |
# +-----------+

# Generated by `vivid generate catppuccin-mocha`
source $ZDOTDIR/env.d/ls_colors.zsh

# +-----+
# | EZA |
# +-----+

# Shared flag set used by the ls alias and FZF_ALT_C_COMMAND below
export EZACMD="eza --color=always --icons=always --group-directories-first -a --classify=auto --dereference"

# +-----+
# | FZF |
# +-----+

export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix --hidden --follow --exclude .git"

export FZF_DEFAULT_OPTS="
  --color bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8
  --color fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc
  --color marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8
  --color selected-bg:#45475a
  --color border:#313244,label:#cdd6f4
  --color header:italic
  --border rounded
  --border-label-pos center
  --layout reverse
  --info right
  --prompt ' : '
  --pointer ''
  --marker '✓'
  --preview-window 'right:65%'
  --ansi
  --tmux 90%"

# Ctrl+T — file search
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export FZF_CTRL_T_OPTS="
  --border-label ' 󰱽 File Search '
  --preview 'bat {}'
  --header '📌 ⌃O to Open | ⌃Y to Copy | ⌃E to Edit'
  --bind 'ctrl-o:become(open -R {})'
  --bind 'ctrl-y:become(echo -n {} | pbcopy)'
  --bind 'ctrl-e:become(tmux new-window $EDITOR -p {+1})'
  --select-1 --exit-0"

# Ctrl+R — command history
export FZF_CTRL_R_OPTS="
  --border-label '  Command History '
  --bind 'ctrl-y:become(echo -n {2..} | pbcopy)'
  --header '📌 ⌃Y to Copy'"

# Alt+C — directory jump
export FZF_ALT_C_COMMAND="fd --type d --strip-cwd-prefix --hidden --follow --exclude .git"
export FZF_ALT_C_OPTS="
  --border-label '   Directory Explorer '
  --preview '$EZACMD --tree --level=2 {}'"
