#!/usr/bin/env zsh

_sesh-sessions () {
  exec </dev/tty
  exec <&1
  local session
  session=$(sesh list -t -c | fzf --border-label '  TMUX Session Manager (sesh) ' --border --prompt '⚡  ' --select-1 --exit-0)
  zle reset-prompt > /dev/null 2>&1 || true

  if [[ -z "$session" ]]; then
    return
  fi

  sesh connect $session
}
