#!/usr/bin/env zsh

# A clearer "smart dot" widget
_zsh-dot() {
  # If the buffer ends with "..", expand it to "../.."
  if [[ $LBUFFER == *.. ]]; then
    LBUFFER+=/..
  # Otherwise, just insert the dot
  else
    LBUFFER+="."
  fi
}
