#!/usr/bin/env zsh

# Set cursor shape as I-beam before prompt, switch to block before executing commands
# https://invisible-island.net/ncurses/terminfo.ti.html#toc-_X_T_E_R_M__Features
# Ss - set cursor shape, usually 6 as argument means I-beam

_zsh-cursor-shape-ibeam() {
    echoti Ss 6
}
