#!/usr/bin/env zsh

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Neovim
rg --line-number "${*:-}" |
	fzf \
		--color "hl:-1:underline,hl+:-1:underline:reverse" \
		--delimiter : \
		--preview 'bat {1} --highlight-line {2}' \
		--preview-window '+{2}+3/3,~3' \
		--bind 'enter:become(nvim {1} +{2})'
